### PR TITLE
(WIP) sig-based code refactor

### PR DESCRIPTION
**Pull request by aupiff**
READY TO MERGE. **I'm not going to get to items 3 and 4 of the checklist tonight, but we should be merging smaller PRs***

This PR eliminates much of the pre-existing code by eliminating the `Friend` relationship and "pending" debts by confirming debts via cryptographic signatures.

TODO:

- [x] debt logging tests
- [x] `Stake.sol` cleanup
- [ ] more `CreditProtocol.sol` and `Stake.sol` integration tests
- [ ] `txLevel` decay tests
- [x] update old tests (Currently, only `test/CreditProtocol.js` is used)

### CODE REVIEW

**Comment by ghost** [comment]
"Creditor" and "Debtor" might not make sense as the labels for the two users, since we really just have a deterministic ordering of the two ids. I'd rather have a convention for negative balance being debt, positive being credit, and just calling them `p1` and `p2`.

**Comment by ghost** [comment]
Missing currency recording in this version--that's pretty critical data to include. It could solved in two ways:
* make debt balances a struct of balance and currency code
* hash an ascii currency code at the start or end of the debt hash, and require each ucac to maintain a list of the currency codes they use so that all balances can be computed offline.

I think the latter solution (or a variation thereof) is pretty obviously preferable from an efficiency standpoint.

**Comment by aupiff** [comment]
I was thinking that each UCAC would deal in only a single currency that you could set exactly once, when the UCAC was created.

Regarding your comment about debtor / creditor, I was thinking that the credit amount would always be positive (`uint256`), and that depending on how they're ordered, the creditor-debtor (or whatever the UCAC interprets it as) relationship would be clear. In our balance mappings, their relationships will always be accessed like `map[min(p1, p2)][max(p1,p2)]`, but that doesn't mean we need to order them as `min(p1, p2) max(p1,p2)` in the logs.

**Comment by aupiff** [comment]
I'm still not clear on what the interaction between the UCAC contract and `Stake.sol` and `CreditProtocol.sol` should be. We'll have to discuss this while developing the new FiD prototype.

**Comment by aupiff** [comment]
@timgalebach go ahead and merge this if your review goes well. I am not ignoring your comments; they will be addressed tomorrow after we discuss a few things.

**Pull request merged**
